Feature/add subscribers
budougumi0617/blog-kpi-collector pull request #1
Opened 2019-01-24 06:39 UTC by nagamoto

読者数を取得する箇所を追加しました。
何か問題あればご指摘くださいm(__)m

2019-01-24 07:02 UTC, nagamoto commented on src/appsscript.json
> +  "timeZone": "Asia/Tokyo",
現状では動作に影響はないもののタイムゾーンをついでに東京に変更

2019-01-24 07:02 UTC, nagamoto commented on src/appsscript.json
> +    }]
analyticsを有効に設定

2019-01-24 08:34 UTC, budougumi0617 requested changes
早速のPRありがとうございます！！！！
少しコメントしたのでご確認おねがいします。

2019-01-24 08:34 UTC, budougumi0617 commented on .gitignore
> -src/appsscript.json
これは必要な記述なので削除しないでほしいです。リポジトリには不要なファイルなので。
後述の通り`appscript.json`は配布できないんです。

2019-01-24 08:34 UTC, budougumi0617 commented on src/appsscript.json
> +{
このファイルは削除してください。
理由は、`appscript.json`ファイルはリポジトリに含めていても`clasp create`したときに初期化されるので、意味が無いからです。

```
$ clasp create --title "KPI Sheet" --type sheets --rootDir ./src
Created new Google Sheet: https://drive.google.com/open?id=...
Created new Google Sheets Add-on script: https://script.google.com/d/1.../edit
Cloned 1 file.
└─ ./src/appsscript.json
```
ここで`appscript.json`は初期化されます。

2019-01-24 08:34 UTC, budougumi0617 commented on src/hatena.ts
> +function getBookmarkCount(target) {
ありがとうございます！！

2019-01-24 08:34 UTC, budougumi0617 commented on src/main.ts
> +  if (blogUrl != null) {
はてなブログじゃない人はこのロジックはつかえないですよね？
はてなブックマーク数は取得したいけど、はてなブログじゃないひとはいると思います（というか私）。
なので、`BLOG_URL`が設定されていてかつ`String.prototype.includes()`あたりではてなのURLをなのか絞る必要があると思います。

2019-01-24 08:34 UTC, budougumi0617 commented on src/main.ts
> +  sheet.appendRow([today, followers, pv, bounceRate, bookmarks, numOfSubscribers]);
余裕があればREADMEに読者数を取得する旨追加していただけると 🙏 （このへん）

```
このリポジトリを使ってApps Scriptとスプレットシートを作成すると、以下のKPI情報をシートに書き込んでいきます。  
未設定にしておけば取得もしないので、全てサービスからの情報が不要な方でも利用できます。 
後述するトリガーを設定しておくことで定期的にデータを集計できます。 


Twitter | フォロワー数
Google Analytics | 前日までの週間PV数、 前日までの週間直帰率
はてなブックマーク | はてなブックマーク総数

```

2019-01-24 11:16 UTC, nagamoto commented on src/main.ts
> +  if (blogUrl != null) {
確かに全くその通りですね、考慮が足りてませんでした
はてなブログproの場合もあるはずなので、それも加味しつつ、正規表現など判定が難しそうであれば、別のpropertyを使うなど考えてみます

2019-01-24 11:18 UTC, nagamoto commented on src/main.ts
> +  sheet.appendRow([today, followers, pv, bounceRate, bookmarks, numOfSubscribers]);
承知しました
コメントいただいた箇所以外にも、改善した後にREADMEに記載したほうがいいことがないか、再確認します

2019-01-24 13:34 UTC, budougumi0617 commented on src/main.ts
> +  if (blogUrl != null) {
簡単にオンオフ用のプロパティ追加でもいいと思います！
エラーが出ないならばdone better than perfectで！

2019-01-24 14:22 UTC, nagamoto commented on src/appsscript.sample.json
> +}
実際のappsscript.jsonをGit管理できないことは把握しました
似たように実際の設定ファイルをGit管理できないものは、.sampleをつけてGit管理下に置くような運用をすることが多いので、appsscript.sample.jsonを作成してみました
不要そうであれば削除するので言ってください

2019-01-24 15:41 UTC, budougumi0617 reviewed
なんどもごめんなさい、suggest書きました！

2019-01-24 15:41 UTC, budougumi0617 commented on README.md
> +| `HATENA_BLOG` | true or another | はてなブログ読者数を取得する、未設定もしくはtrue以外の設定は未入力と同じく値を取得しない | true |
```suggestion
| `HATENA_BLOG` | true or another | `BLOG_URL`が設定済みであることがであることが前提。はてなブログ読者数を取得する、未設定もしくはtrue以外の設定は未入力と同じく値を取得しない | true |
```

って感じですかね？

2019-01-24 15:41 UTC, budougumi0617 commented on src/main.ts
> +  if (hatenaBlog === "true") {
```suggestion
  if (hatenaBlog === "true" && blogUrl != null) {
```
ってしないと、`hatenaBlog`だけプロパティがあったとき`null`が返ってました（まあエラーで落ちたりはしないのでいいと言えばいいのですが）

2019-01-25 00:32 UTC, budougumi0617 approved these changes
LGTM!

2019-01-25 00:33 UTC, merged

2019-01-25 00:41 UTC, nagamoto commented
丁寧にレビュいただいてありがとうございましたm(__)m